title: Spectacle.js template
address: Châtillon, France
institution: ONERA, The French Aerospace Lab
date: 2021-03-30
authors:
  - name: Julien Vanharen
    position: Research engineer
    mail: julien.vanharen@onera.fr
    website: jvanhare.github.io
    github: https://github.com/jvanhare
    scholar: https://scholar.google.com/citations?hl=en&user=R6OO3noAAAAJ
    institution: ONERA - DMPE/PLM
    institution_alt: The French Aerospace Lab
    institution_website: https://www.onera.fr/en

  - name: John Doe
  - name: Jane Doe
